name: oseer_health_bridge
description: Oseer HealthBridge - Android companion app for Oseer health platform
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Health integration - Updated version
  health: ^12.0.0
  
  # Authentication
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.0
  crypto: ^3.0.3
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1

  # Networking
  dio: ^5.3.2
  http: ^1.1.0  # Adding http package for debugging
  
  # Storage
  shared_preferences: ^2.2.0
  
  # UI & Animation
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  
  # Utils
  url_launcher: ^6.1.14
  intl: ^0.18.1
  uuid: ^4.0.0
  logger: ^2.0.2
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  app_links: ^3.4.5
  qr_flutter: ^4.1.0
  permission_handler: ^10.4.3
  
  # Adding share_plus for sharing functionality
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

# Flutter app icon configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_adaptive.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700